import react, { useEffect, useState } from 'react';
import Head from 'next/head';
import { ThemeProvider } from 'styled-components';
import GlobalStyles from '../styles/Global';
import { Header, Hero, HeroText, TitleText } from '../styles/styles';
import MovieWrapper from '../components/MovieWrapper';

const theme = {
  colors: {
    header: '#292929',
    body: '#fff',
    footer: '#ebfbff',
  },
  iphone: '320px',
  ipad: '992px',
  desktop: '1030px',
};

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <GlobalStyles />
      <Head>
        <title>Test app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <TitleText>MyTestApp</TitleText>
      </Header>
      <Hero>
        <HeroText>Watch something incredible.</HeroText>
      </Hero>
      <MovieWrapper />
    </ThemeProvider>
  );
}
